export const Data = [
  {
    id: "1",
    name: "things fall apart",
    description:
      "Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum",
    category: "drama",
    author: "chinua achebe",
    rating: 1.5,
    price: 50.4,
    brand: "Nike",
    countInSock: 14,
    numReviews: 10,
    image: "/items/project1.jpg",
  },
  {
    id: "2",
    name: "Arrow of God",
    description:
      "Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum",
    category: "science fiction",
    author: "chinua",
    rating: 0.5,
    price: 500.4,
    brand: "Nike",
    countInSock: 0,
    numReviews: 12,
    image: "/items/project2.jpg",
  },
  {
    id: "3",
    name: "lucas life",
    description:
      "Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum",
    category: "poetry",
    author: "lucas",
    rating: 0.2,
    price: 51.4,
    brand: "Nike",
    countInSock: 20,
    numReviews: 15,
    image: "/items/project3.jpg",
  },
  {
    id: "4",
    name: "things fall in shape",
    description:
      "Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum",
    category: "life drama",
    author: "ken",
    rating: 1.0,
    price: 40.1,
    brand: "Nike",
    countInSock: 18,
    numReviews: 5,
    image: "/items/project4.jpg",
  },
  {
    id: "5",
    name: "game of throne",
    description:
      "Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum",
    category: "prose",
    author: "zion",
    rating: 0.7,
    price: 20.55,
    brand: "Nike",
    countInSock: 14,
    numReviews: 28,
    image: "/items/project5.jpg",
  },
  {
    id: "6",
    name: "blindspot",
    description:
      "Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum",
    category: "drama",
    author: "jane",
    rating: 0.3,
    price: 100.0,
    brand: "Nike",
    countInSock: 0,
    numReviews: 30,
    image: "/items/project6.jpg",
  },
];
